---
title: "week_7_excercises_data"
author: "J.Blondeau"
date: "2023-10-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


This week is all about making plots and graphs in ggplot2.  The only datasets you need are in the /data directory.

1) sttstj_fish_biomass
2) taxonomic


Inspect the sttstj_fish_biomass dataset.  It is 3 years of biomass (kg/177m2) data for 9 fish species inside the VI national park (prot = 1) and outside the national park (prot = 0). 

In this instance, anytime you need to group by and summarize, you can just take the mean of biomass and SE.  This would not always be appropriate, but for this case the exercises are for plotting and graphing.

**put all your code in the .Rmd file inside a code chunk for each question.  Annotate what you are doing so that you can reference them later.

1. Create a line graph of biomass over time for Red hind ("EPI GUTT") inside the national park.

2. Create a point and line graph of biomass over time for Yellowtail Snapper ("OCY CHRY") outside the national park.

3. Create a bar graph of biomass over time for each species grouped by protected_status.  Edit the the axis and legend titles to be more insightful.
    - biomass units
    - Scientific name instead of SPECIES_CD
    - 0 = Open, 1 = VI National Park
    
4. Create a bar graph of trophic-level mean biomass inside and outside VI national park for each species.

5. Create a point and line plot of 'grouper' biomass (+- SE) over time; inside and outside park together.